"""Build PDF / DOCX exports for student transcripts."""
from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak

from docx import Document
from docx.shared import Pt, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH


# ─────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────
def _esc(s: str) -> str:
    """Escape a string for reportlab Paragraph."""
    return (s or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _meta_line(meta: dict) -> str:
    parts = []
    if meta.get("student"):  parts.append(f"<b>Student:</b> {_esc(meta['student'])}")
    if meta.get("file"):     parts.append(f"<b>File:</b> {_esc(meta['file'])}")
    if meta.get("grade"):    parts.append(f"<b>Grade:</b> {meta['grade']}")
    if meta.get("subject"):  parts.append(f"<b>Subject:</b> {_esc(meta['subject'])}")
    if meta.get("chapter"):  parts.append(f"<b>Chapter:</b> {_esc(meta['chapter'])}")
    if meta.get("marks") is not None and meta.get("marks_total") is not None:
        parts.append(f"<b>Marks:</b> {meta['marks']}/{meta['marks_total']}")
    return " · ".join(parts)


# ─────────────────────────────────────────────────────────────────────────
# PDF export
# ─────────────────────────────────────────────────────────────────────────
def transcripts_to_pdf(items: list[dict[str, Any]]) -> bytes:
    """Render one PDF containing all transcripts (one per page-ish, with header)."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=18*mm, rightMargin=18*mm,
                            topMargin=18*mm, bottomMargin=18*mm)
    styles = getSampleStyleSheet()
    h_style = ParagraphStyle("h", parent=styles["Heading2"], fontSize=14,
                             textColor=colors.HexColor("#1e1b4b"))
    meta_style = ParagraphStyle("meta", parent=styles["BodyText"], fontSize=10,
                                textColor=colors.HexColor("#475569"))
    body_style = ParagraphStyle("body", parent=styles["BodyText"], fontSize=11,
                                leading=15, fontName="Helvetica",
                                textColor=colors.HexColor("#0f172a"))
    foot_style = ParagraphStyle("foot", parent=styles["BodyText"], fontSize=9,
                                textColor=colors.HexColor("#94a3b8"),
                                alignment=2)

    story = []
    for i, item in enumerate(items):
        meta = item.get("meta", {})
        text = item.get("text", "") or ""
        header_title = meta.get("title") or f"Transcript {i + 1}"
        story.append(Paragraph(_esc(header_title), h_style))
        ml = _meta_line(meta)
        if ml:
            story.append(Paragraph(ml, meta_style))
        story.append(Spacer(1, 8))
        for para in text.split("\n"):
            line = _esc(para).strip()
            story.append(Paragraph(line or "&nbsp;", body_style))
        story.append(Spacer(1, 6))
        story.append(Paragraph(
            f"Generated by Codevidhya · {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            foot_style))
        if i + 1 < len(items):
            story.append(PageBreak())

    doc.build(story)
    return buf.getvalue()


# ─────────────────────────────────────────────────────────────────────────
# DOCX export
# ─────────────────────────────────────────────────────────────────────────
def transcripts_to_docx(items: list[dict[str, Any]]) -> bytes:
    doc = Document()
    style = doc.styles["Normal"]
    style.font.name = "Calibri"; style.font.size = Pt(11)

    for i, item in enumerate(items):
        meta = item.get("meta", {})
        text = item.get("text", "") or ""

        title = doc.add_heading(meta.get("title") or f"Transcript {i + 1}", level=2)
        title.alignment = WD_ALIGN_PARAGRAPH.LEFT

        # Meta line
        meta_bits = []
        if meta.get("student"): meta_bits.append(("Student", str(meta["student"])))
        if meta.get("file"):    meta_bits.append(("File",    str(meta["file"])))
        if meta.get("grade"):   meta_bits.append(("Grade",   str(meta["grade"])))
        if meta.get("subject"): meta_bits.append(("Subject", str(meta["subject"])))
        if meta.get("chapter"): meta_bits.append(("Chapter", str(meta["chapter"])))
        if meta.get("marks") is not None and meta.get("marks_total") is not None:
            meta_bits.append(("Marks", f"{meta['marks']}/{meta['marks_total']}"))
        if meta_bits:
            p = doc.add_paragraph()
            for idx, (k, v) in enumerate(meta_bits):
                if idx: p.add_run("  ·  ")
                r1 = p.add_run(f"{k}: "); r1.bold = True
                p.add_run(v)
            p.runs[0].font.color.rgb = RGBColor(0x47, 0x55, 0x69)

        doc.add_paragraph()  # spacer

        # Body — keep paragraph breaks
        for para in text.split("\n"):
            doc.add_paragraph(para)

        # Footer
        foot = doc.add_paragraph(f"Generated by Codevidhya · {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        foot.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        foot.runs[0].font.size = Pt(9)
        foot.runs[0].font.color.rgb = RGBColor(0x94, 0xa3, 0xb8)

        if i + 1 < len(items):
            doc.add_page_break()

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
